name: Actualitza AgendaCulturalBCN

on:
  schedule:
    # Cada dia a les 06:30 UTC (canvia si vols). Cron: minut hora dia-mes dia-setmana
    - cron: '30 6 * * *'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script (genera .ics)
        run: |
          python agenda_cultural_bcn.py

      - name: Commit and push ICS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add AgendaCulturalBCN.ics || true
          git commit -m "Actualització automàtica AgendaCulturalBCN" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
      - name: Instalar dependencias
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

            - name: Instalar dependencias
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt

