name: Actualizar calendario

on:
  schedule:
    - cron: '0 7 * * *'  # se ejecuta todos los días a las 07:00 UTC
  workflow_dispatch:

jobs:
  generate_ics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Instalar librerías
        run: pip install ics
      - name: Generar calendario
        run: python generate_ics.py
      - name: Subir .ics a GitHub Pages
        run: mv agenda-renoir.ics ./  # tu repo ya debe estar configurado con GitHub Pages
