name: Actualiza calendario cultural BCN

on:
  push:
    branches:
      - main

jobs:
  generate_ics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generar archivo .ics
        run: python generate_ics.py

      - name: Subir archivo .ics
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add agenda-cultural-bcn.ics
          git commit -m 'Actualizar calendario'
          git push

