name: Actualizar calendario

on:
  schedule:
    - cron: '0 7 * * *'  # se ejecuta todos los días a las 07:00 UTC
  workflow_dispatch:

jobs:
  generate_ics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar librerías necesarias
        run: pip install ics

      - name: Generar calendario .ics
        run: python generate_ics.py

      - name: Subir archivo .ics a GitHub Pages
        run: |
          mv agenda-renoir.ics ./  # asegurarse de que el archivo quede en la raíz
